### ISSUE TITLE
Recursive reload if confirm to reload.

### ISSUE THREAD

**Issue by FlandreDaisuki** [eight04/hijack-worker#1]
Like Facebook, Youtube, ...

Maybe the script check can change to
```
[...document.querySelectorAll("script")]
  .filter(x => x.textContent.includes('Worker'))
  .length
```
but it'll be failed if code are obfuscated.

**Comment by FlandreDaisuki** [comment]
> If you are using Tampermonkey, you can change "Config mode" to "Advanced" then change "Inject Mode" to "Instant" in the settings, so the script would be executed faster.

It's work. 🎉

**Comment by eight04** [comment]
There are still some cases that the injection is not fast enough:

1. The userscript is newly installed. I guess this is due to that the script is not cached.
2. There are only inline scripts on the page, and the page is navigated through history backward/forward. I think this is because the page is already cached and it loads before the userscript.

Also, the validation:

```js
if (document.querySelector("script")) {
	...
}
```

doesn't work well in (2) situation. The entire DOM is ready while the userscript is injected i.e. script elements are available, but they are not executed yet. I'm going to remove the validation.
